spring:
  application:
    name: order-service

  #rabbitmq 추가
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #spring-cloud-config
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: order-service

greeting:
  message: welcome to sinple e-comerce
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
