server:
  port: 8000
spring:
  application:
    name: zuul-service

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8081
    second-service:
      path: /second-service/**
      url: http://localhost:8082

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
