FROM mysql:8.0

# 환경 변수 설정 (외부 .env 파일에서 로드)
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_ROOT_HOST: "%"

# 데이터베이스 초기화 SQL 스크립트 (선택 사항)
#COPY ./init.sql /docker-entrypoint-initdb.d/
#권한설정
#COPY ./init.sql /docker-entrypoint-initdb.d/

CMD ["bash", "-c", "docker-entrypoint.sh mysqld & \
    while ! mysqladmin ping -hlocalhost --silent; do sleep 2; done && \
    mysql -u root -p${MYSQL_ROOT_PASSWORD} -e \"CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';\" && \
    mysql -u root -p${MYSQL_ROOT_PASSWORD} -e \"GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%'; FLUSH PRIVILEGES;\" && \
    tail -f /dev/null"]
EXPOSE 3306