server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file://Users/an-yeongjun/study/microservice-study/git-local-repo
          uri: file:///C:\Users\안영준\study\microservice-study\git-local-repo
          default-label: master
