server:
  port: 8888


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://Users/an-yeongjun/study/microservice-study/git-local-repo
          default-label: master
